-- ============================================================================
-- PC Parts Depot - catalog schema (Oracle Database 21c)
-- ----------------------------------------------------------------------------
-- Run as the application schema/user (created by the deploy script).
-- Idempotent: drops and recreates the catalog tables so it can be re-run.
-- ============================================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CATEGORIES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE CATEGORIES (
    CODE         VARCHAR2(16)  NOT NULL,
    NAME         VARCHAR2(64)  NOT NULL,
    DESCRIPTION  VARCHAR2(256),
    CONSTRAINT PK_CATEGORIES PRIMARY KEY (CODE)
);

CREATE TABLE PRODUCTS (
    ID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    SKU           VARCHAR2(48)   NOT NULL,
    NAME          VARCHAR2(160)  NOT NULL,
    CATEGORY_CODE VARCHAR2(16)   NOT NULL,
    BRAND         VARCHAR2(48),
    PRICE         NUMBER(10, 2)  DEFAULT 0 NOT NULL,
    SPECS         VARCHAR2(512),
    STOCK         NUMBER(8)      DEFAULT 0 NOT NULL,
    IMAGE_URL     VARCHAR2(256),
    DESCRIPTION   VARCHAR2(1024),
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID),
    CONSTRAINT UQ_PRODUCTS_SKU UNIQUE (SKU),
    CONSTRAINT FK_PRODUCTS_CATEGORY
        FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORIES (CODE)
);

CREATE INDEX IX_PRODUCTS_CATEGORY ON PRODUCTS (CATEGORY_CODE);
CREATE INDEX IX_PRODUCTS_BRAND    ON PRODUCTS (BRAND);

COMMIT;
