-- ==========================================================================
-- PC Parts Depot - demo inventory seed data (Oracle Database 21c)
-- --------------------------------------------------------------------------
-- Run AFTER schema.sql, as the application schema/user.
-- Idempotent: clears existing rows before inserting.
-- ==========================================================================

DELETE FROM PRODUCTS;
DELETE FROM CATEGORIES;

INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('CPU', 'Processors', 'Desktop CPUs from AMD and Intel');
INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('GPU', 'Graphics Cards', 'Discrete gaming and workstation GPUs');
INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('RAM', 'Memory', 'DDR4 and DDR5 memory kits');
INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('SSD', 'Storage', 'NVMe SSDs, SATA SSDs and hard drives');
INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('MBD', 'Motherboards', 'ATX, mATX and ITX motherboards');
INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('PSU', 'Power Supplies', '80 PLUS rated ATX power supplies');
INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('CASE', 'Cases', 'Mid-tower, full-tower and ITX PC cases');
INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('COOL', 'Cooling', 'Air and liquid CPU coolers');
INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('MON', 'Monitors', 'Gaming and productivity monitors');
INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('KBD', 'Keyboards', 'Mechanical and membrane keyboards');
INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('MOU', 'Mice', 'Wired and wireless gaming mice');
INSERT INTO CATEGORIES (CODE, NAME, DESCRIPTION) VALUES ('PRE', 'Prebuilt PCs', 'Ready-to-go desktop systems');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (1, 'CPU-AMD-7800X3D', 'AMD Ryzen 7 7800X3D', 'CPU', 'AMD', 359.00, '8C/16T, 4.2/5.0GHz, AM5, 96MB L3, 120W', 24, '/images/placeholder.svg', '3D V-Cache gaming flagship for AM5.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (2, 'CPU-AMD-7950X', 'AMD Ryzen 9 7950X', 'CPU', 'AMD', 549.00, '16C/32T, 4.5/5.7GHz, AM5, 80MB cache, 170W', 14, '/images/placeholder.svg', 'Top-tier multithreaded Zen 4 processor.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (3, 'CPU-AMD-7600X', 'AMD Ryzen 5 7600X', 'CPU', 'AMD', 229.00, '6C/12T, 4.7/5.3GHz, AM5, 38MB cache, 105W', 41, '/images/placeholder.svg', 'Mainstream AM5 gaming CPU.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (4, 'CPU-AMD-5700X3D', 'AMD Ryzen 7 5700X3D', 'CPU', 'AMD', 199.00, '8C/16T, 3.0/4.1GHz, AM4, 96MB L3, 105W', 33, '/images/placeholder.svg', 'Budget 3D V-Cache upgrade for AM4.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (5, 'CPU-INT-14900K', 'Intel Core i9-14900K', 'CPU', 'Intel', 569.00, '24C/32T, up to 6.0GHz, LGA1700, 36MB L3', 11, '/images/placeholder.svg', 'Flagship Raptor Lake Refresh CPU.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (6, 'CPU-INT-14700K', 'Intel Core i7-14700K', 'CPU', 'Intel', 399.00, '20C/28T, up to 5.6GHz, LGA1700, 33MB L3', 18, '/images/placeholder.svg', 'High-performance desktop processor.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (7, 'CPU-INT-14600K', 'Intel Core i5-14600K', 'CPU', 'Intel', 309.00, '14C/20T, up to 5.3GHz, LGA1700, 24MB L3', 27, '/images/placeholder.svg', 'Excellent mid-range gaming CPU.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (8, 'CPU-INT-13400F', 'Intel Core i5-13400F', 'CPU', 'Intel', 189.00, '10C/16T, up to 4.6GHz, LGA1700, no iGPU', 38, '/images/placeholder.svg', 'Affordable 10-core for gaming builds.');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (9, 'GPU-NV-4090', 'NVIDIA GeForce RTX 4090 24GB', 'GPU', 'NVIDIA', 1799.00, '24GB GDDR6X, 16384 CUDA, 2520MHz boost', 6, '/images/placeholder.svg', 'Halo-tier 4K and content creation GPU.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (10, 'GPU-NV-4080S', 'NVIDIA GeForce RTX 4080 SUPER 16GB', 'GPU', 'NVIDIA', 999.00, '16GB GDDR6X, 10240 CUDA, 2550MHz boost', 9, '/images/placeholder.svg', 'High-end 4K gaming card.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (11, 'GPU-NV-4070S', 'NVIDIA GeForce RTX 4070 SUPER 12GB', 'GPU', 'NVIDIA', 599.00, '12GB GDDR6X, 7168 CUDA, 2475MHz boost', 16, '/images/placeholder.svg', 'Strong 1440p performance.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (12, 'GPU-NV-4060', 'NVIDIA GeForce RTX 4060 8GB', 'GPU', 'NVIDIA', 299.00, '8GB GDDR6, 3072 CUDA, 2460MHz boost', 30, '/images/placeholder.svg', 'Efficient 1080p gaming GPU.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (13, 'GPU-AMD-7900XTX', 'AMD Radeon RX 7900 XTX 24GB', 'GPU', 'AMD', 949.00, '24GB GDDR6, 6144 SP, RDNA 3, 2500MHz', 8, '/images/placeholder.svg', 'High-VRAM 4K Radeon flagship.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (14, 'GPU-AMD-7800XT', 'AMD Radeon RX 7800 XT 16GB', 'GPU', 'AMD', 499.00, '16GB GDDR6, 3840 SP, RDNA 3', 12, '/images/placeholder.svg', 'Great value 1440p card.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (15, 'GPU-AMD-7600', 'AMD Radeon RX 7600 8GB', 'GPU', 'AMD', 269.00, '8GB GDDR6, 2048 SP, RDNA 3', 22, '/images/placeholder.svg', 'Budget 1080p Radeon.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (16, 'GPU-INT-A770', 'Intel Arc A770 16GB', 'GPU', 'Intel', 279.00, '16GB GDDR6, 4096 ALUs, Xe-HPG', 17, '/images/placeholder.svg', 'Value 1440p card with 16GB VRAM.');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (17, 'RAM-COR-32-6000', 'Corsair Vengeance 32GB DDR5-6000', 'RAM', 'Corsair', 114.00, '2x16GB, DDR5-6000, CL30, 1.35V', 40, '/images/placeholder.svg', 'Enthusiast AM5/Intel DDR5 kit.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (18, 'RAM-GSK-32-6400', 'G.Skill Trident Z5 32GB DDR5-6400', 'RAM', 'G.Skill', 139.00, '2x16GB, DDR5-6400, CL32, RGB', 26, '/images/placeholder.svg', 'High-speed RGB DDR5 kit.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (19, 'RAM-KIN-16-5600', 'Kingston Fury Beast 16GB DDR5-5600', 'RAM', 'Kingston', 59.00, '2x8GB, DDR5-5600, CL36', 55, '/images/placeholder.svg', 'Affordable DDR5 starter kit.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (20, 'RAM-COR-64-5600', 'Corsair Vengeance 64GB DDR5-5600', 'RAM', 'Corsair', 199.00, '2x32GB, DDR5-5600, CL40', 18, '/images/placeholder.svg', 'High-capacity kit for creators.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (21, 'RAM-GSK-32-3600', 'G.Skill Ripjaws V 32GB DDR4-3600', 'RAM', 'G.Skill', 74.00, '2x16GB, DDR4-3600, CL18', 47, '/images/placeholder.svg', 'Proven DDR4 kit for AM4/LGA1200.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (22, 'RAM-CRU-16-3200', 'Crucial 16GB DDR4-3200', 'RAM', 'Crucial', 39.00, '2x8GB, DDR4-3200, CL16', 60, '/images/placeholder.svg', 'Reliable budget DDR4 kit.');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (23, 'SSD-SAM-990-2TB', 'Samsung 990 Pro 2TB NVMe', 'SSD', 'Samsung', 169.00, 'PCIe 4.0, 7450/6900 MB/s, M.2 2280', 33, '/images/placeholder.svg', 'Flagship Gen4 NVMe SSD.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (24, 'SSD-WD-SN850-1TB', 'WD Black SN850X 1TB NVMe', 'SSD', 'Western Digital', 89.00, 'PCIe 4.0, 7300 MB/s read, M.2 2280', 44, '/images/placeholder.svg', 'Top gaming Gen4 SSD.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (25, 'SSD-CRU-T700-2TB', 'Crucial T700 2TB Gen5 NVMe', 'SSD', 'Crucial', 239.00, 'PCIe 5.0, 12400 MB/s read, M.2 2280', 10, '/images/placeholder.svg', 'Cutting-edge Gen5 SSD.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (26, 'SSD-SAM-870-1TB', 'Samsung 870 EVO 1TB SATA', 'SSD', 'Samsung', 79.00, 'SATA III, 560 MB/s, 2.5-inch', 52, '/images/placeholder.svg', 'Dependable SATA SSD.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (27, 'SSD-CRU-MX500-500', 'Crucial MX500 500GB SATA', 'SSD', 'Crucial', 44.00, 'SATA III, 560 MB/s, 2.5-inch', 61, '/images/placeholder.svg', 'Budget 2.5-inch SSD.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (28, 'HDD-SEA-BARR-4TB', 'Seagate BarraCuda 4TB HDD', 'SSD', 'Seagate', 84.00, '3.5-inch, 5400 RPM, SATA, 256MB cache', 29, '/images/placeholder.svg', 'High-capacity mechanical storage.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (29, 'HDD-WD-RED-8TB', 'WD Red Plus 8TB NAS HDD', 'SSD', 'Western Digital', 169.00, '3.5-inch, 5640 RPM, CMR, NAS-rated', 15, '/images/placeholder.svg', 'NAS-optimized hard drive.');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (30, 'MBD-ASU-B650E-F', 'ASUS ROG Strix B650E-F Gaming', 'MBD', 'ASUS', 259.00, 'AM5, DDR5, PCIe 5.0, ATX, Wi-Fi 6E', 15, '/images/placeholder.svg', 'Feature-rich AM5 ATX board.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (31, 'MBD-MSI-B650-T', 'MSI MAG B650 Tomahawk Wi-Fi', 'MBD', 'MSI', 219.00, 'AM5, DDR5, PCIe 4.0, ATX, Wi-Fi 6E', 20, '/images/placeholder.svg', 'Robust VRM mid-range AM5 board.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (32, 'MBD-GIG-X670E', 'Gigabyte X670E Aorus Master', 'MBD', 'Gigabyte', 449.00, 'AM5, DDR5, PCIe 5.0, E-ATX, Wi-Fi 6E', 7, '/images/placeholder.svg', 'High-end overclocking AM5 board.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (33, 'MBD-ASU-Z790-P', 'ASUS Prime Z790-P Wi-Fi', 'MBD', 'ASUS', 229.00, 'LGA1700, DDR5, PCIe 5.0, ATX, Wi-Fi 6', 18, '/images/placeholder.svg', 'Solid Intel Z790 ATX board.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (34, 'MBD-MSI-B760M', 'MSI Pro B760M-A Wi-Fi', 'MBD', 'MSI', 139.00, 'LGA1700, DDR5, mATX, Wi-Fi 6', 26, '/images/placeholder.svg', 'Compact value Intel board.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (35, 'MBD-ASR-B550M', 'ASRock B550M Pro4', 'MBD', 'ASRock', 99.00, 'AM4, DDR4, PCIe 4.0, mATX', 34, '/images/placeholder.svg', 'Affordable AM4 micro-ATX board.');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (36, 'PSU-SEA-GX850', 'Seasonic Focus GX-850 850W', 'PSU', 'Seasonic', 129.00, '850W, 80+ Gold, fully modular, ATX 3.0', 27, '/images/placeholder.svg', 'Reliable 80+ Gold PSU.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (37, 'PSU-COR-RM1000', 'Corsair RM1000e 1000W', 'PSU', 'Corsair', 159.00, '1000W, 80+ Gold, fully modular, ATX 3.0', 19, '/images/placeholder.svg', 'High-wattage PSU with PCIe 5.0.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (38, 'PSU-EVG-650G', 'EVGA SuperNOVA 650 GT 650W', 'PSU', 'EVGA', 89.00, '650W, 80+ Gold, fully modular', 31, '/images/placeholder.svg', 'Compact mid-power PSU.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (39, 'PSU-BEQ-750', 'be quiet! Pure Power 12 M 750W', 'PSU', 'be quiet!', 109.00, '750W, 80+ Gold, modular, ATX 3.0', 23, '/images/placeholder.svg', 'Quiet and efficient 750W PSU.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (40, 'PSU-COR-SF750', 'Corsair SF750 750W SFX', 'PSU', 'Corsair', 149.00, '750W, 80+ Platinum, SFX, modular', 12, '/images/placeholder.svg', 'Premium SFX PSU for ITX builds.');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (41, 'CASE-LIA-O11D', 'Lian Li O11 Dynamic EVO', 'CASE', 'Lian Li', 169.00, 'Mid-tower, dual-chamber, tempered glass, E-ATX', 16, '/images/placeholder.svg', 'Popular showcase chassis.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (42, 'CASE-FRA-NORTH', 'Fractal Design North', 'CASE', 'Fractal Design', 139.00, 'Mid-tower, wood front, mesh, ATX', 21, '/images/placeholder.svg', 'Stylish airflow-focused case.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (43, 'CASE-NZX-H7F', 'NZXT H7 Flow', 'CASE', 'NZXT', 129.00, 'Mid-tower, high airflow mesh, ATX', 24, '/images/placeholder.svg', 'Clean-look airflow mid-tower.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (44, 'CASE-COR-4000D', 'Corsair 4000D Airflow', 'CASE', 'Corsair', 94.00, 'Mid-tower, mesh front, ATX', 30, '/images/placeholder.svg', 'Best-selling airflow case.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (45, 'CASE-COO-NR200', 'Cooler Master NR200P', 'CASE', 'Cooler Master', 109.00, 'Mini-ITX, SFF, tempered glass', 14, '/images/placeholder.svg', 'Compact ITX SFF case.');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (46, 'COOL-NOC-D15', 'Noctua NH-D15 chromax.black', 'COOL', 'Noctua', 109.00, 'Dual-tower air, 2x140mm fans, 165W TDP', 22, '/images/placeholder.svg', 'Legendary high-end air cooler.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (47, 'COOL-ARC-LF360', 'Arctic Liquid Freezer III 360', 'COOL', 'Arctic', 79.00, '360mm AIO, 3x120mm, VRM fan', 26, '/images/placeholder.svg', 'High-value 360mm liquid cooler.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (48, 'COOL-COR-H150', 'Corsair iCUE H150i Elite 360', 'COOL', 'Corsair', 189.00, '360mm AIO, RGB, LCD-ready', 13, '/images/placeholder.svg', 'Premium RGB 360mm AIO.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (49, 'COOL-BEQ-DR4', 'be quiet! Dark Rock Pro 4', 'COOL', 'be quiet!', 89.00, 'Dual-tower air, 250W TDP, quiet', 19, '/images/placeholder.svg', 'Silent high-performance air cooler.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (50, 'COOL-DEE-AK400', 'DeepCool AK400', 'COOL', 'DeepCool', 34.00, 'Single-tower air, 120mm, 220W TDP', 40, '/images/placeholder.svg', 'Excellent budget air cooler.');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (51, 'MON-LG-27GP850', 'LG UltraGear 27GP850-B 27 inch', 'MON', 'LG', 379.00, '27 inch QHD, IPS, 165Hz, 1ms, G-Sync', 17, '/images/placeholder.svg', 'Fast 1440p IPS gaming monitor.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (52, 'MON-SAM-G7-32', 'Samsung Odyssey G7 32 inch', 'MON', 'Samsung', 549.00, '32 inch QHD, VA, 240Hz, 1ms, curved', 9, '/images/placeholder.svg', 'High-refresh curved gaming monitor.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (53, 'MON-DEL-S2722QC', 'Dell S2722QC 27 inch 4K', 'MON', 'Dell', 319.00, '27 inch 4K UHD, IPS, 60Hz, USB-C 65W', 14, '/images/placeholder.svg', 'Sharp 4K productivity monitor.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (54, 'MON-AOC-24G2', 'AOC 24G2 24 inch', 'MON', 'AOC', 149.00, '24 inch FHD, IPS, 144Hz, 1ms', 33, '/images/placeholder.svg', 'Affordable 1080p esports monitor.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (55, 'MON-ASU-PG27AQDM', 'ASUS ROG Swift PG27AQDM 27 inch', 'MON', 'ASUS', 899.00, '27 inch QHD, OLED, 240Hz, 0.03ms', 5, '/images/placeholder.svg', 'Premium OLED gaming monitor.');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (56, 'KBD-KEY-V3MAX', 'Keychron V3 Max', 'KBD', 'Keychron', 99.00, 'TKL, wireless, hot-swap, gasket mount', 28, '/images/placeholder.svg', 'Customizable wireless mechanical board.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (57, 'KBD-COR-K70', 'Corsair K70 RGB Pro', 'KBD', 'Corsair', 139.00, 'Full-size, Cherry MX, RGB, USB pass', 20, '/images/placeholder.svg', 'Durable gaming keyboard.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (58, 'KBD-LOG-G915', 'Logitech G915 TKL', 'KBD', 'Logitech', 199.00, 'TKL, low-profile, wireless, RGB', 11, '/images/placeholder.svg', 'Premium low-profile wireless board.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (59, 'KBD-RAZ-HUNT', 'Razer Huntsman V3 Pro', 'KBD', 'Razer', 189.00, 'Full-size, analog optical, RGB', 13, '/images/placeholder.svg', 'Analog optical gaming keyboard.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (60, 'KBD-RK-61', 'Royal Kludge RK61', 'KBD', 'Royal Kludge', 45.00, '60%, wireless, hot-swap, RGB', 37, '/images/placeholder.svg', 'Budget 60% mechanical board.');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (61, 'MOU-LOG-GPXSW', 'Logitech G Pro X Superlight 2', 'MOU', 'Logitech', 159.00, 'Wireless, 60g, HERO 2 sensor, 32K DPI', 24, '/images/placeholder.svg', 'Esports wireless mouse.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (62, 'MOU-RAZ-VIPERV3', 'Razer Viper V3 Pro', 'MOU', 'Razer', 149.00, 'Wireless, 54g, Focus Pro 35K', 18, '/images/placeholder.svg', 'Ultralight competitive mouse.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (63, 'MOU-GLO-MODEL-O', 'Glorious Model O 2 Wireless', 'MOU', 'Glorious', 79.00, 'Wireless, 59g, BAMF 2.0 sensor', 29, '/images/placeholder.svg', 'Lightweight honeycomb mouse.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (64, 'MOU-COR-M65', 'Corsair M65 RGB Ultra', 'MOU', 'Corsair', 59.00, 'Wired, FPS, adjustable weight, 26K DPI', 26, '/images/placeholder.svg', 'FPS-focused wired mouse.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (65, 'MOU-LOG-MX3S', 'Logitech MX Master 3S', 'MOU', 'Logitech', 99.00, 'Wireless, ergonomic, 8K DPI, quiet', 31, '/images/placeholder.svg', 'Productivity ergonomic mouse.');

INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (66, 'PRE-STARTER-R5', 'Depot Starter - Ryzen 5 / RTX 4060', 'PRE', 'PC Parts Depot', 999.00, 'R5 7600, RTX 4060, 16GB DDR5, 1TB NVMe', 10, '/images/placeholder.svg', 'Entry 1080p gaming desktop.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (67, 'PRE-GAMER-R7', 'Depot Gamer - Ryzen 7 / RTX 4070S', 'PRE', 'PC Parts Depot', 1599.00, 'R7 7800X3D, RTX 4070 SUPER, 32GB DDR5, 2TB', 7, '/images/placeholder.svg', 'Mainstream 1440p gaming desktop.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (68, 'PRE-PRO-I7', 'Depot Pro - Core i7 / RTX 4080S', 'PRE', 'PC Parts Depot', 2299.00, 'i7-14700K, RTX 4080 SUPER, 32GB DDR5, 2TB', 5, '/images/placeholder.svg', 'High-end gaming and creator PC.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (69, 'PRE-ULTRA-I9', 'Depot Ultra - Core i9 / RTX 4090', 'PRE', 'PC Parts Depot', 3499.00, 'i9-14900K, RTX 4090, 64GB DDR5, 4TB', 3, '/images/placeholder.svg', 'No-compromise 4K powerhouse.');
INSERT INTO PRODUCTS (ID, SKU, NAME, CATEGORY_CODE, BRAND, PRICE, SPECS, STOCK, IMAGE_URL, DESCRIPTION) VALUES (70, 'PRE-WORK-R9', 'Depot Workstation - Ryzen 9', 'PRE', 'PC Parts Depot', 2799.00, 'R9 7950X, RTX 4080 SUPER, 64GB DDR5, 4TB', 4, '/images/placeholder.svg', 'Multithreaded content-creation rig.');

COMMIT;
